# TrustyAI
TRUSTYAI_SERVICE = "trustyai-service"
TRUSTYAI_SERVICE_IMAGE = "quay.io/trustyaiservice/trustyai-service"
MM_PAYLOAD_PROCESSORS = "MM_PAYLOAD_PROCESSORS"

# TrustyAI Generic Endpoints
TRUSTYAI_NAMES_ENDPOINT = "/info/names"
TRUSTYAI_MODEL_METADATA_ENDPOINT = "/info"
TRUSTYAI_UPLOAD_ENDPOINT = "/data/upload"

# TrustyAI Metrics Endpoints
TRUSTYAI_SCHEDULE = "request"
TRUSTYAI_METRICS = "metrics"

# TrustyAI Bias Metrics Endpoints
TRUSTYAI_SPD_ENDPOINT = f"{TRUSTYAI_METRICS}/group/fairness/spd"

# TrustyAI Drift Metrics Endpoints
TRUSTYAI_METRICS_DRIFT = f"{TRUSTYAI_METRICS}/drift"
TRUSTYAI_MEANSHIFT = "meanshift"
TRUSTYAI_FOURIERMMD = "fouriermmd"
TRUSTYAI_KSTEST = "kstest"
TRUSTYAI_APPROXKSTEST = "approxkstest"

TRUSTYAI_MEANSHIFT_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_MEANSHIFT}"
TRUSTYAI_MEANSHIFT_SCHEDULE_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_MEANSHIFT}/{TRUSTYAI_SCHEDULE}"
TRUSTYAI_FOURIERMMD_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_FOURIERMMD}"
TRUSTYAI_FOURIERMMD_SCHEDULE_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_FOURIERMMD}/{TRUSTYAI_SCHEDULE}"
TRUSTYAI_KSTEST_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_KSTEST}"
TRUSTYAI_KSTEST_SCHEDULE_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_KSTEST}/{TRUSTYAI_SCHEDULE}"
TRUSTYAI_APPROXKSTEST_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_APPROXKSTEST}"
TRUSTYAI_APPROXKSTEST_SCHEDULE_ENDPOINT = f"/{TRUSTYAI_METRICS_DRIFT}/{TRUSTYAI_APPROXKSTEST}/{TRUSTYAI_SCHEDULE}"

# Model Serving
OVMS = "ovms"
OVMS_RUNTIME_NAME = f"{OVMS}-1.x"
OVMS_QUAY_IMAGE = "quay.io/opendatahub/openvino_model_server:stable"
OPENVINO_MODEL_FORMAT = "openvino_ir"

MLSERVER = "mlserver"
MLSERVER_RUNTIME_NAME = f"{MLSERVER}-1.x"
MLSERVER_QUAY_IMAGE = "quay.io/aaguirre/mlserver:1.3.2"  # TODO: Change it to TrustyAI specific quay

# Model Format
ONNX = "onnx"
SKLEARN = "sklearn"
XGBOOST = "xgboost"

# API Groups
KSERVE_API_GROUP = "serving.kserve.io"
TRUSTYAI_API_GROUP = "trustyai.opendatahub.io"

# InferenceService
INFERENCE_ENDPOINT = "/infer"

# Minio
MINIO_IMAGE = "quay.io/trustyai/modelmesh-minio-examples:gauss"

# Protocol Versions
GRPC = "grpc"

# OpenDataHub
OPENDATAHUB_IO = "opendatahub.io"

MODEL_DATA_PATH = "./model_data"
